### ISSUE TITLE
Make the best from semantic versionning when using Simple Token Authentication

### ISSUE THREAD

**Issue by gonzalo-bulnes** [thoulike/rails-api-authentication-token-example#1]
Hello @thoulike!

Publishing this example app seems to me a very good initiative!
I'll write to you a few comments related to _Simple Token Authentication_, in distinct issues so you can choose what to do with each of them independently.

---

Simple Token Authentication follows the [semantic versionning](http://semver.org) principles. Behind those principles is the idea that it should be simple to know if gem updates are (or are not) backward compatible, so keeping them up-to-date is both easy and safe.

With Simple Token Authentication, if you require the gem as follows (see the gem [installation instructions](https://github.com/gonzalo-bulnes/simple_token_authentication/tree/v1.7.0#installation)), then running `bundle update simple_token_authentication` will always install the most recent version of the gem which is backward compatible with the v1.x.x series.

``` ruby
# Gemfile

gem 'simple_token_authentication', '~> 1.0' # see semver.org
```

Modifying [this Gemfile line](https://github.com/thoulike/rails-api-authentication-token-example/commit/f18c4f5f46c674975d716dc284dcab220efed27b#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R8) would ensure that any person who clone this repository to get the latest version of _Simple Token Authentication_ (compatible with v1.6.0), which is [v1.7.0](https://github.com/gonzalo-bulnes/simple_token_authentication/releases/tag/v1.7.0) at the time of writing.

**Comment by ghost** [comment]
Hi, @gonzalo-bulnes.

I'm glad to see v1.7.0 of the gem and very thankful. Rails-api support seems to render this example obsolete and blatantly pointless.

There are only two things that are still valid.

https://github.com/thoulike/rails-api-authentication-token-example/commit/6df8f981f98e502441eacc2a72c1a6bba55cc8e7 - I need to check if this is still needed.

http://provoost.tumblr.com/post/80873086965/json-api-authentication-using-devise-tokens - in my example there's no need to subclass Devise controllers.

I mean, everybody should know that there is no need to subclass them, there's to many tutorials all over the internet suggesting that, which is unnecessary and/or obsolete.

And I'd love my example to become pointless. Then everybody could rely on your gem. If this is the case, then maybe you could somehow suggest that there's no need to subclass and that the gem is "all you need" in gem's readme.

**Comment by ghost** [comment]
https://github.com/thoulike/rails-api-authentication-token-example/commit/6df8f981f98e502441eacc2a72c1a6bba55cc8e7 - well, as for me, this is still needed.

@gonzalo-bulnes, how do you approach this out of the box?

By "this" I mean accessing Devise by AJAX calls (or maybe everybody knows "respond_to :json" and everybody using rails-api can think of the first two lines of https://github.com/thoulike/rails-api-authentication-token-example/commit/6df8f981f98e502441eacc2a72c1a6bba55cc8e7, and all I've been doing around this issue makes no sense?).

Also how do you approach this in regular Rails (adding :json to navigational_formats or is "respond_to :json" enough)?

It might be more of a Devise flaw, but your gem is kind of a fix of Devise for APIs, so maybe there's a way to do something about it inside your gem?

**Comment by ghost** [comment]
@gonzalo-bulnes, I know this might not be the best place to have this discussion, but if you could follow up on this, I'd greatly appreciate that.

**Comment by gonzalo-bulnes** [comment]
Hi @thoulike,

In a Rails app, `respond_to :json` should be enough.
About the Rails::API case, including the modules is necessary (see documentation about [additional modules](https://github.com/rails-api/rails-api#adding-other-modules)). Both of them.

**Comment by ghost** [comment]
Thank you very much @gonzalo-bulnes!
