### ISSUE TITLE
Use Simple Token Authentication v1.7.0 or higher for out-of-the-box Rails::API support

### ISSUE THREAD

**Issue by gonzalo-bulnes** [thoulike/rails-api-authentication-token-example#2]
_Simple Token Authentication_ **v1.7.0** [does support Rails::API](https://github.com/gonzalo-bulnes/simple_token_authentication/releases/tag/v1.7.0)! That means [this line can be removed](https://github.com/thoulike/rails-api-authentication-token-example/commit/1da163152a9d1ff5ac2786ae05fa913a9e557bae#diff-55c5b7aecfb519d0e4880eaf2788eb6eR4) form the `ApplicationController` definition.

Let's mention that there is not reason not to use _Simple Token Authentication_ v1.7.0, since it is backward compatible with v1.6.0 (see #1).

**Comment by ghost** [comment]
https://github.com/thoulike/rails-api-authentication-token-example/commit/62d7c940542d29d6be0c2bef8768aa114fefd403
