### ISSUE TITLE
Use the Simple Token Authentication defaults to make configuration simpler

### ISSUE THREAD

**Issue by gonzalo-bulnes** [thoulike/rails-api-authentication-token-example#3]
It's possible to make the _Simple Token Authentication_-related configuration of the `AController` a bit simpler, since the following code is equivalent to [the original implementation](https://github.com/thoulike/rails-api-authentication-token-example/blob/1da163152a9d1ff5ac2786ae05fa913a9e557bae/app/controllers/a_controller.rb#L2-L3) :

``` ruby
class AController < ApplicationController
  acts_as_token_authentication_handler_for User

  def asdf
    render :json => { :message => 'Well done!' }
  end
end
```

**Comment by ghost** [comment]
https://github.com/thoulike/rails-api-authentication-token-example/commit/62d7c940542d29d6be0c2bef8768aa114fefd403
